language: node_js
sudo: required
node_js:
  - "8"

cache:
  directories:
    - "node_modules"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install software-properties-common -y -qq
  - npm i -g ganache-cli truffle

install:
  - npm install

script:
  - npm run coverage 

after_script:
  - cat coverage/lcov.info
